# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c956e2b69d2041dca7f393ce6a741371e230d1075ca3b9a554bfe19b5672fc1dcd36d36b319ff22de77adab805e19ef332e2ded516be77e33fb22adb57c6d850

test:
  secret_key_base: 039c8d4dc322d8300c391ca4bdd7231c69d3348727a681bf5d9e0476a2e6e7b8380ea6093c01128945a9972ef186fd7a4445ee8e85ba04cc936fceacb117ad4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
